### ISSUE TITLE
Cover base file and base file's thickness is 0mm on JLC3DP

### ISSUE THREAD

**Issue by haneu123** [whowechina/diva_pico#1]
English:
Hello, I tried to import the cover base file and base into 3D Monkey (Jialichuang 3D Printing), but it shows that the thickness of these two files is 0mm and cannot be used . Does this model file need to be used for printing with Bambu 3D printer?
Looking forward to your reply, my English is not very good. Thank you so much.

Simplified Chinese:
大佬你好，我尝试把cover base文件和base导入三维猴（嘉立创3D打印），但是上面显示这两个文件的厚度均为0mm，无法用于打印。请问是不是这个模型文件需要用拓竹3D打印机才能用于打印。
期待大佬的回复，英语不太好，谢谢了。

![QQ截图20240706105601](https://github.com/whowechina/diva_pico/assets/12793692/51a693a7-9971-43f7-b172-63ef8fa0af74)
![QQ截图20240706105619](https://github.com/whowechina/diva_pico/assets/12793692/97cef5f5-87c4-4e01-bb3c-4e1ea03962fd)

**Comment by whowechina** [comment]
我试了一下，似乎它有最小壁厚太薄的提醒，点开来有“接受风险下单“和”咨询客服“的选项，你问问它们客服看。
这个文件没有限定是什么打印机，只要够大，且是 0.4mm 喷头，PLA/PETG 都没问题。
注意打印时底部不能翘边，翘边就作废了。
